export const API_CONFIG = {
  // BASE_URL: import.meta.env.VITE_API_BASE_URL || 'https://api.clique83.com',
  BASE_URL: import.meta.env.VITE_API_BASE_URL || 'https://clique-staging.fly.dev',
  ENDPOINTS: {
    LOGIN: '/admin/login',
    ANALYTICS: '/admin/analytics',
    REVENUE_ANALYTICS: '/admin/analytics/revenue',
    LIFECYCLE_ANALYTICS: '/admin/analytics/lifecycle',
    USERS: '/admin/users',
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    PENDING_PROFILES: '/admin/pending-profiles',
    APPROVE_USER: (id: string) => `/admin/users/${id}/approve`,
    REJECT_USER: (id: string) => `/admin/users/${id}/reject`,
    PHOTO_VISIBILITY: (id: string) => `/admin/users/${id}/photo-visibility`,
    SUGGESTIONS: '/admin/suggestions',
    SUGGESTION_DETAIL: (id: string) => `/admin/suggestions/${id}`,
    UNMATCHED: '/admin/unmatched',
    MANUAL_MATCH: '/admin/manual-match',
    CHECK_DEADLINES: '/suggestions/admin/check-deadlines',
    MEETINGS: '/admin/meetings',
    LOCATIONS: '/meetings/locations',
    LOCATION_DETAIL: (id: string) => `/meetings/locations/${id}`,
    SEED_DATA: '/admin/analytics/seed',
    CLEANUP_DATA: '/admin/analytics/cleanup',
    FORCE_MATCH: '/test/force-match',
  },
};
